build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python py2-pip
    - pip install --no-cache-dir docker-compose
    - docker-compose -v
  script:
  - docker-compose -f docker-compose.debug.yml up
