version: '2'
services:
  cmake-debug:
    image: cppseed_cmake-debug:0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: "Debug"

  build-debug:
    depends_on:
      - cmake-debug
    image: cppseed_cmake-debug:0.1
    env_file:
      - ./compiler.env
    command: ["sh", "-c", "make", "all"]
  test-debug:
    depends_on:
      - build-debug
      - cmake-debug
    image: cppseed_cmake-debug:0.1
    env_file:
      - ./compiler.env
    command: ["sh", "-c", "ctest"]